FROM node:18

WORKDIR /app

# Copier les fichiers package.json depuis le dossier frontend
COPY ../frontend/package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source du frontend
COPY ../frontend/ . .

# Exposer le port
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]
