FROM node:18

WORKDIR /app

# Copier les fichiers package.json depuis le dossier Backend (qui est à côté de docker/)
COPY ../Backend/package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source du backend
COPY ../Backend/ . .

# Exposer le port
EXPOSE 3004

# Démarrer l'application
CMD ["npm", "start"]
